spring.application.name=recipe

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.api-docs.resolve-schema-properties=true

spoonacular.API_BASE_URL=https://api.spoonacular.com
spoonacular.api_key=4f27fa1813ee4300be4dc5e3165b9ffe

